#page title
page_title                                :  Barcodica - Barcode scanner on iOS and Android                                 # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1672434160                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=dev.martinsv.barcodescanner                                          # Enter Google Play Store URL.
presskit_download_link                    :                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Barcodica                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Barcode scanner                                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Effortlessly manage inventory with Barcodica app. Scan, track quantities, import data, and export in seconds. The ultimate barcode scanner app.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Martins Vasiljevs
your_link                                 :
your_city                                 :
email_address                             : martinsv.dev@gmail.com
facebook_username                         :                                           
instagram_username                        :
twitter_username                          :
github_username                           :
youtube_username                          :
mastodon_link                             :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Three types of scanners
    description                           : Choose from a screen-based scanner for speed, a button-based scanner for battery optimization, or a continuous scanning mode for convenience.
    fontawesome_icon_name                 : barcode
    
  - title                                 : Create product records
    description                           : Match barcodes with detailed product information, including name, price, images, and more. Every time you scan the barcode, the saved data will be displayed.
    fontawesome_icon_name                 : eye

  - title                                 : Seamless integration
    description                           : Import products from your sales or inventory system effortlessly.
    fontawesome_icon_name                 : thumbs-up

  - title                                 : Quantity tracking
    description                           : Scan the same barcode repeatedly, and the quantity will be automatically incremented. Edit quantities easily.
    fontawesome_icon_name                 : exchange

  - title                                 : Handy search option
    description                           : Quickly find scanned barcodes using the search functionality.
    fontawesome_icon_name                 : search
  
  - title                                 : Share and export
    description                           : Share your scanned barcode list in CSV, customizable with the columns you need.
    fontawesome_icon_name                 :

  - title                                 : Expired product management
    description                           : Add expiration dates and easily identify expired products.
    fontawesome_icon_name                 : check-square-o

  - title                                 : Advanced settings
    description                           : Set up additional scanner settings to prevent duplicate barcodes or combine similar ones.
    fontawesome_icon_name                 : cogs

  - title                                 : Label scanned barcodes with color
    description                           : Helps to identify products that need attention.
    fontawesome_icon_name                 : tag



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
